image: Visual Studio 2017
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
        Update-AppveyorBuild -Version "SNAPSHOT-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
install:
  - nuget restore
platform:
  - x86
  - x64
configuration: Release
build:
  parallel: true
  project: DePvr.sln
artifacts:
  - path: DePvr\bin\$(platform)\$(configuration)
